name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo secret
        run: echo "Secret is ${{ secrets.OPENAI_KEY }}"

